name: prune-juice

version: '0.6'
maintainer: Dan Fithian <daniel.m.fithian@gmail.com>
license: MIT
copyright: 2020 Dan Fithian
category: Development
synopsis: 'Prune unused Haskell dependencies'
description: 'Prune unused Haskell dependencies - see README at <https://github.com/dfithian/prune-juice#readme>'
github: dfithian/prune-juice

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-redundant-constraints
  - -Wincomplete-uni-patterns
  - -eventlog

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - aeson == 1.5.6.0
  - base < 5.0
  - bytestring == 0.10.12.0
  - Cabal == 3.2.1.0
  - cabal-install-parsers == 0.3.0.1
  - containers == 0.6.2.1
  - directory == 1.3.6.0
  - filepath == 1.4.2.1
  - megaparsec == 9.0.1
  - monad-logger == 0.3.36
  - mtl == 2.2.2
  - process == 1.6.9.0
  - text == 1.2.4.1
  - yaml == 0.11.5.0

extra-source-files:
  - stack.yaml
  - cabal.project
  - prune-juice.cabal
  - test/fixtures/*

library:
  source-dirs:
    - src

tests:
  test:
    main: main.hs
    source-dirs:
      - test
    dependencies:
      - file-embed == 0.0.13.0
      - file-path-th == 0.1.0.0
      - hspec == 2.7.8

      - prune-juice

executables:
  prune-juice:
    main: main.hs
    source-dirs:
      - app
    dependencies:
      - optparse-applicative == 0.15.1.0

      - prune-juice
